import { maturityQuestions } from '../ndmoData.js'
const T = [
  [/strateg/i, 'a strategy document', ['Hold a short workshop with business heads to list today’s data problems and goals.', 'Write the strategy: vision, objectives, initiatives, KPIs and a roadmap. Use the “It must cover” list as your table of contents.', 'Send the draft to the Data Management Office, Legal and Security; record their comments and fix them.', 'Present it to the Data Management Committee / authority holder and obtain a signed approval.', 'Publish it and store the approved, version-numbered copy as evidence.']],
  [/plan|roadmap/i, 'an approved implementation plan', ['Baseline: assess where the entity stands today against this specification.', 'List the initiatives needed, each with owner, start/end dates and budget.', 'Prioritise them (high impact, low effort first) and set milestones.', 'Get the plan approved by the committee.', 'Report status regularly (not started / in progress / complete / delayed, % complete).']],
  [/polic|standard|guideline/i, 'a policy or standard document', ['Check existing entity policies and NDMO / NCA regulations to find gaps.', 'Draft it on your document template: purpose, scope, policy statements, roles, document control (version, owner, approval date).', 'Turn every item in “It must cover” into a numbered policy statement.', 'Review with stakeholders, then approve through the governance committee.', 'Publish and circulate it; keep acknowledgement records and review it yearly.']],
  [/process|procedure|workflow|lifecycle/i, 'a documented process that is actually running', ['Map today’s steps: who does what, in which system.', 'Design the target process: steps, inputs, outputs, owners, timelines (SLA) and escalation path.', 'Write it as a procedure with a flow diagram and get it approved.', 'Set up the tool or form that runs the process and train the people involved.', 'Run it for real and keep logs, tickets or registers that prove it is used.']],
  [/train|awareness/i, 'a training and awareness programme', ['Identify the audiences (executives, owners, stewards, all staff) and what each must know.', 'Prepare the content and a yearly schedule.', 'Deliver the sessions; keep attendance sheets and feedback.', 'Measure effectiveness (quiz or survey) and update the content next cycle.']],
  [/role|officer|committee|organi[sz]|steward|owner|manual/i, 'defined and formally appointed roles', ['List each role the specification requires and its responsibilities.', 'Write job descriptions or terms of reference.', 'Issue signed appointment letters / committee decisions.', 'Publish the structure and an RACI chart; hold the first meeting and keep the minutes.']],
  [/kpi|performance|monitor|measure/i, 'a KPI and monitoring mechanism', ['Define each KPI: name, owner, equation, unit, baseline, target, frequency, data source.', 'Collect the data on the agreed schedule (automate where possible).', 'Produce a periodic report with scorecards and trends.', 'Get the report approved and record the improvement actions.']],
  [/audit|complian/i, 'a compliance audit cycle', ['Build an audit checklist from this specification and related policies.', 'Plan the audit: scope, auditors, dates; notify the owners.', 'Run it and write a findings report with severity and owner.', 'Track corrective actions to closure and re-check.']],
  [/tool|solution|platform|catalog|metadata|register|inventory|repository|architecture|artifact/i, 'a working tool, register or artifact', ['Decide exactly what must be captured (fields/attributes) from “It must cover”.', 'Select or configure the tool or template (existing platform, spreadsheet or register).', 'Fill it with real data and assign an owner who keeps it up to date.', 'Review it for completeness and get it approved.', 'Keep screenshots, exports or the file itself (dated) as evidence.']],
]
const DEFAULT = ['Read each requirement and decide which document, record or system change would prove it.', 'Assign one accountable owner and a due date.', 'Create the document / change the process or system.', 'Review and approve it through your governance route.', 'Save dated evidence and tick the item here.']
const ROLES = /(Data Governance Officer|Data Management Office|Chief Data Officer|Data Governance Committee|Data Management Committee|Data Owner|Data Steward|Data Custodian|Authority Holder|Business Owner|Information Security|Legal|NDMO|NCA)/gi
export function guide(spec) {
  const t = spec.text, parts = t.split(/\s(?=\d+\.\s)/), hit = T.find(x => x[0].test(spec.name))
  const requirements = parts.length > 1 ? parts.slice(1) : t.split(/(?<=\.)\s+(?=[A-Z])/).filter(x => /shall|must|should/i.test(x))
  const evidence = []
  spec.ndi.forEach(n => (maturityQuestions[n.mq]?.levels[n.level]?.items || []).forEach(i => evidence.push({ mq: n.mq, level: n.level, text: i.evidence })))
  return {
    deliverable: hit ? hit[1] : 'the control described by this specification', requirements, steps: hit ? hit[2] : DEFAULT, evidence,
    roles: [...new Set((t.match(ROLES) || []).map(r => r.replace(/\b\w/g, c => c.toUpperCase())))],
    frequency: (t.match(/(annually|quarterly|monthly|periodically|at least (once )?(a|per) (year|quarter|month)|every [\w ]{1,20}(year|month)s?)/i) || [])[0] || '',
  }
}
