import { useState, useEffect } from 'react'
import { useApp } from '../lib/store.jsx'
import { universe } from '../lib/items.js'
import { download } from '../lib/exporter.js'
import { ASEC } from './TopBar.jsx'
import { RegLibrary } from './Library.jsx'
const Box = ({ title, children }) => <section className="rounded-xl border bg-white p-4 shadow-sm"><h3 className="mb-3 font-semibold text-ksa">{title}</h3>{children}</section>
const inp = 'rounded-lg border px-2 py-1.5 text-sm', btn = 'rounded-lg bg-ksa px-3 py-1.5 text-sm text-white', btn2 = 'rounded-lg border border-ksa px-3 py-1.5 text-sm text-ksa', danger = 'rounded-lg border border-red-600 px-3 py-1.5 text-sm text-red-600'
const ERR = { cannot_delete_self: 'You cannot delete your own account', ldap_user: 'Directory accounts have no local password', username_taken: 'That username already exists', last_admin: 'At least one active admin is required', weak_password: 'Password must be at least 8 characters', bad_username: 'Username: 3–40 letters, numbers, . _ -' }
const run = async fn => { try { return await fn() } catch (e) { alert(ERR[e.message] || e.message) } }
const rnd = (a, b) => Math.floor(a + Math.random() * (b - a + 1)), pick = a => a[rnd(0, a.length - 1)], day = o => new Date(Date.now() + o * 864e5).toISOString()
const DEPTS = ['Data Governance Office', 'IT', 'Legal & Compliance', 'Risk', 'Operations']
const makeSample = (items, pct, names) => items.map((i, n) => {
  const owner = pick(names), reviewer = pick(names.filter(x => x !== owner).length ? names.filter(x => x !== owner) : names), dept = DEPTS[names.indexOf(owner) % DEPTS.length]
  if (Math.random() * 100 < pct) { const o = -rnd(1, 120), r = Math.random(), wf = r < .2 ? 'Evidence Submitted' : r < .4 ? 'Under Review' : r < .85 ? 'Verified Compliant' : r < .95 ? 'Partially Compliant' : 'Non-Compliant'
    return { k: i.key, done: true, date: day(o), due: day(o + rnd(-7, 10)).slice(0, 10), start: day(o - rnd(5, 30)).slice(0, 10), owner, reviewer, dept, by: owner, wf, pct: 100, ref: `EV-${1000 + n}`, note: 'Sample data', sample: true } }
  const wf = pick(['In Progress', 'In Progress', 'Not Started', 'Not Started']), od = Math.random() < .35
  return { k: i.key, done: false, due: day(od ? -rnd(1, 45) : rnd(1, 75)).slice(0, 10), start: day(-rnd(1, 40)).slice(0, 10), owner, reviewer, dept, by: owner, wf, pct: wf === 'Not Started' ? 0 : rnd(10, 80), ref: '', note: 'Sample data', sample: true }
})
function Users() {
  const { call, user } = useApp(), [list, setList] = useState([]), [f, setF] = useState({ u: '', d: '', r: 'contributor', p: '', t: 'native' }), load = () => call('app_list_users').then(setList).catch(e => alert(e.message)); useEffect(() => { load() }, [])
  const upd = (u, patch) => run(async () => { const x = { ...u, ...patch }; await call('app_update_user', { p_uid: u.id, p_display: x.display_name, p_role: x.role, p_active: x.active, p_unlock: !!patch.unlock }); load() })
  return (<div className="space-y-4"><Box title="Create user"><div className="mb-3 flex gap-4 text-sm"><label><input type="radio" checked={f.t === 'native'} onChange={() => setF({ ...f, t: 'native' })} /> Native user (password stored in the tracker)</label><label><input type="radio" checked={f.t === 'ldap'} onChange={() => setF({ ...f, t: 'ldap' })} /> Directory user (Active Directory / LDAP)</label></div>
    <div className="flex flex-wrap items-end gap-2"><input placeholder={f.t === 'ldap' ? 'Directory username (e.g. sAMAccountName)' : 'Username'} value={f.u} onChange={e => setF({ ...f, u: e.target.value })} className={inp + ' w-64'} /><input placeholder="Display name" value={f.d} onChange={e => setF({ ...f, d: e.target.value })} className={inp} />
      <select value={f.r} onChange={e => setF({ ...f, r: e.target.value })} className={inp}><option value="contributor">Contributor (can update)</option><option value="viewer">Viewer (read only)</option><option value="admin">Admin</option></select>
      {f.t === 'native' && <input type="password" placeholder="Temporary password (min 8)" value={f.p} onChange={e => setF({ ...f, p: e.target.value })} className={inp} />}
      <button className={btn} onClick={() => run(async () => { await call('app_create_user', { p_username: f.u, p_display: f.d, p_role: f.r, p_password: f.p, p_auth: f.t }); setF({ u: '', d: '', r: 'contributor', p: '', t: f.t }); load() })}>Create</button></div>
    <p className="mt-2 text-xs text-slate-500">{f.t === 'ldap' ? 'The user signs in with their directory password. Set up the connection under Security & policies → Directory sign-in.' : 'The user must set their own password at first sign-in.'}</p></Box>
    <Box title={`Users (${list.length})`}><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="p-1">Username</th><th>Name</th><th>Type</th><th>Role</th><th>Active</th><th>Last login</th><th>Actions</th></tr></thead>
      <tbody>{list.map(u => <tr key={u.id} className="border-b"><td className="p-1 font-medium">{u.username}{u.locked && <span className="ml-1 rounded bg-red-100 px-1 text-xs text-red-700">locked</span>}{u.is_sample && <span className="ml-1 rounded bg-amber-100 px-1 text-xs text-amber-700">sample</span>}</td><td>{u.display_name}</td><td className="text-xs">{u.auth_type === 'ldap' ? 'Directory' : 'Native'}</td>
        <td><select value={u.role} onChange={e => upd(u, { role: e.target.value })} className={inp}><option value="admin">admin</option><option value="contributor">contributor</option><option value="viewer">viewer</option></select></td>
        <td><input type="checkbox" checked={u.active} onChange={e => upd(u, { active: e.target.checked })} /></td><td className="text-xs">{u.last_login ? new Date(u.last_login).toLocaleString('en-GB') : '—'}</td>
        <td className="space-x-2 text-xs">{u.auth_type !== 'ldap' && <button className="text-ksa underline" onClick={() => { const p = prompt(`New temporary password for ${u.username} (min 8 characters)`); p && run(() => call('app_reset_password', { p_uid: u.id, p_password: p }).then(() => alert('Password reset – the user must change it at next sign-in'))) }}>Reset password</button>}
          {u.locked && <button className="text-ksa underline" onClick={() => upd(u, { unlock: true })}>Unlock</button>}<button className="text-slate-600 underline" onClick={() => run(() => call('app_revoke_sessions', { p_uid: u.id }).then(() => alert('Signed out')))}>Sign out</button>
          {u.username !== user && <button className="text-red-600 underline" onClick={() => confirm(`Delete user ${u.username}?`) && run(async () => { await call('app_delete_user', { p_uid: u.id }); load() })}>Delete</button>}</td></tr>)}</tbody></table></div></Box></div>)
}
function Ldap() {
  const { tok } = useApp(), [r, setR] = useState(null), [busy, setBusy] = useState(false)
  const test = async () => { setBusy(true); try { const x = await fetch('/api/ldap-test', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tok }) }); setR(await x.json()) } catch { setR({ error: 'The /api endpoint is only available on the Vercel deployment (not with npm run dev).' }) } setBusy(false) }
  const ok = v => v === true ? '✔' : v === false ? '✘' : '—'
  return (<Box title="Directory sign-in (Active Directory / LDAP)"><p className="mb-2 text-sm text-slate-600">Directory users are created in Users & roles (type “Directory”). Their password is checked against your directory by a server function on Vercel; the tracker never stores it. The directory must be reachable from Vercel (LDAPS).</p>
    <ol className="list-decimal space-y-1 pl-5 text-sm"><li>In Vercel → Settings → Environment Variables add: <code>LDAP_URL</code> (ldaps://host:636), <code>LDAP_BASE_DN</code>, <code>LDAP_BIND_DN</code> and <code>LDAP_BIND_PASSWORD</code> (read-only service account), <code>LDAP_USER_ATTR</code> (sAMAccountName for AD, uid for OpenLDAP) and <code>LDAP_SHARED_SECRET</code> (any random text of 16+ characters).</li>
      <li>In Supabase SQL Editor run, with the same secret: <code className="break-all">insert into app_meta values ('ldap_secret','YOUR-SECRET') on conflict (key) do update set value = excluded.value;</code></li><li>Redeploy on Vercel, then press Test connection.</li></ol>
    <button onClick={test} disabled={busy} className={btn2 + ' mt-3'}>{busy ? 'Testing…' : 'Test connection'}</button>
    {r && <div className="mt-2 rounded bg-slate-50 p-2 text-xs">{r.error && !r.configured ? <p className="text-red-700">{r.error}</p> : <ul className="space-y-0.5"><li>Directory settings present: {ok(r.configured)} {r.url}</li><li>Base DN: {r.baseDn || '—'}</li><li>Shared secret set on Vercel: {ok(r.secretSet)}</li><li>Service-account bind: {ok(r.bindOk)} {r.error}</li></ul>}</div>}</Box>)
}
function Security() {
  const { call } = useApp()
  return (<div className="space-y-4"><Box title="Roles"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="p-1">Capability</th><th>Viewer</th><th>Contributor</th><th>Admin</th></tr></thead><tbody>
    {[['View all content, dashboard, exports, emails', 1, 1, 1], ['Update status, owner, dates, notes', 0, 1, 1], ['Attach / submit evidence', 0, 1, 1], ['Set compliance verdicts (named reviewer)', 0, 1, 1], ['Edit menu, library files, branding', 0, 0, 1], ['Manage users, security, sample data, backups', 0, 0, 1]].map(r => <tr key={r[0]} className="border-b"><td className="p-1">{r[0]}</td>{r.slice(1).map((x, i) => <td key={i}>{x ? '✔' : '—'}</td>)}</tr>)}</tbody></table></Box>
    <Ldap />
    <Box title="Security policy in force"><ul className="list-disc space-y-1 pl-5 text-sm"><li>Native passwords are stored as salted bcrypt hashes; minimum 8 characters; new and reset accounts must change them at first sign-in.</li><li>Directory users never have a password in the tracker.</li><li>5 wrong passwords lock a native account for 15 minutes (admins can unlock).</li><li>Sessions expire after 12 hours; admins can force sign-out.</li><li>All reads/writes go through server functions that check the role; tables are not reachable from the browser.</li><li>Every sign-in, change, export and clear action is written to the audit log.</li></ul>
      <button className={danger + ' mt-3'} onClick={() => confirm('Sign out every other user now?') && run(() => call('app_revoke_sessions', {}).then(() => alert('Done')))}>Sign out all other users</button></Box></div>)
}
function Audit() {
  const { call } = useApp(), [rows, setRows] = useState([]), load = () => call('app_audit', { p_limit: 300 }).then(setRows).catch(e => alert(e.message)); useEffect(() => { load() }, [])
  return <Box title="Audit log (latest 300)"><button className={btn2 + ' mb-2'} onClick={load}>Refresh</button><div className="max-h-[32rem] overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b text-slate-500"><th className="p-1">When</th><th>User</th><th>Action</th><th>Detail</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-b"><td className="p-1 whitespace-nowrap">{new Date(r.at).toLocaleString('en-GB')}</td><td>{r.username}</td><td>{r.action}</td><td className="break-all">{r.detail}</td></tr>)}</tbody></table></div></Box>
}
function Branding() {
  const { settings, saveSetting } = useApp(), [hex, setHex] = useState(settings.color), [title, setTitle] = useState(settings.title ?? 'NDMO / NDI Compliance Tracker'), [sub, setSub] = useState(settings.subtitle ?? 'NDMO v1.5 · NDI v1.1 · OE 2026')
  const up = k => e => { const f = e.target.files[0]; if (!f) return; if (f.size > 400 * 1024) return alert('Image must be under 400 KB'); const r = new FileReader(); r.onload = () => run(() => saveSetting(k, r.result)); r.readAsDataURL(f) }
  const setC = c => { setHex(c); /^#[0-9a-f]{6}$/i.test(c) && run(() => saveSetting('color', c)) }
  const Img = ({ k, l, h }) => <div className="mb-4"><p className="text-sm font-medium">{l}</p><p className="text-xs text-slate-500">{h}</p><div className="mt-1 flex items-center gap-3">{settings[k] ? <img src={settings[k]} alt={l} className="max-h-16 rounded border bg-white p-1" /> : <span className="text-xs text-slate-400">None</span>}<input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={up(k)} className="text-xs" />{settings[k] && <button className="text-xs text-red-600 underline" onClick={() => run(() => saveSetting(k, null))}>Remove</button>}</div></div>
  return (<div className="grid gap-4 md:grid-cols-2"><Box title="Header text"><label className="block text-xs text-slate-600">Header name<input value={title} onChange={e => setTitle(e.target.value)} className={inp + ' mt-0.5 w-full'} /></label>
    <label className="mt-2 block text-xs text-slate-600">Line below the header name<input value={sub} onChange={e => setSub(e.target.value)} className={inp + ' mt-0.5 w-full'} /></label>
    <div className="mt-3 flex gap-2"><button className={btn} onClick={() => run(async () => { await saveSetting('title', title); await saveSetting('subtitle', sub) })}>Save header text</button><button className={btn2} onClick={() => run(async () => { setTitle('NDMO / NDI Compliance Tracker'); setSub('NDMO v1.5 · NDI v1.1 · OE 2026'); await saveSetting('title', 'NDMO / NDI Compliance Tracker'); await saveSetting('subtitle', 'NDMO v1.5 · NDI v1.1 · OE 2026') })}>Restore default</button></div></Box>
    <Box title="Theme colour (all users)"><div className="flex items-center gap-3"><input type="color" value={/^#[0-9a-f]{6}$/i.test(hex) ? hex : '#006C35'} onChange={e => setC(e.target.value)} className="h-10 w-14 cursor-pointer" /><input value={hex} onChange={e => setC(e.target.value)} maxLength={7} className="w-32 rounded border px-3 py-2 font-mono text-sm" /></div>
      <div className="mt-3 flex gap-2">{['#006C35', '#0B5394', '#7B1FA2', '#B71C1C', '#E65100', '#37474F'].map(c => <button key={c} onClick={() => setC(c)} style={{ background: c }} aria-label={c} className="h-7 w-7 rounded-full border" />)}</div></Box>
    <Box title="Logo, signature & seal"><Img k="logo" l="Logo" h="Top-left of the site, login page and all exports." /><Img k="signature" l="Signature" h="Printed on exported reports." /><Img k="seal" l="Seal / stamp" h="Printed on exported reports." /></Box></div>)
}
function Sample() {
  const { call, refresh } = useApp(), [pct, setPct] = useState(70), [busy, setBusy] = useState(false), [users, setUsers] = useState([]), w = async fn => { setBusy(true); await run(fn); await refresh(); setBusy(false) }
  const loadU = () => call('app_list_users').then(l => setUsers(l.filter(u => u.is_sample))).catch(() => {}); useEffect(() => { loadU() }, [])
  return (<div className="space-y-4"><Box title="Populate sample data"><p className="mb-3 text-sm text-slate-600">Creates sample contributor accounts (password <b>Demo@123</b>) and fills every requirement with demo statuses. Each record is owned, submitted and reviewed by one of these real accounts, so you can sign in as them. Real data is never overwritten.</p>
    <label className="text-sm">Evidence submitted or later: <b>{pct}%</b><input type="range" min="0" max="100" value={pct} onChange={e => setPct(+e.target.value)} className="ml-3 align-middle" /></label>
    <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className={btn} onClick={() => w(async () => { const us = await call('app_create_sample_users'); const n = await call('app_bulk_progress', { p_rows: makeSample(universe(), pct, us.map(u => u.username)), p_wipe: true }); await loadU(); alert(`${us.length} sample users ready and ${n} items filled`) })}>{busy ? 'Working…' : 'Populate / regenerate sample data'}</button>
      <button disabled={busy} className={btn2} onClick={() => confirm('Remove sample records AND sample users?') && w(async () => { await call('app_clear', { p_what: 'sample' }); await loadU() })}>Clear sample data & users</button></div>
    {users.length > 0 && <p className="mt-3 text-xs text-slate-600">Sample users (password Demo@123): {users.map(u => u.username).join(', ')}</p>}</Box>
    <Box title="Danger zone"><p className="mb-2 text-sm text-slate-600">Erases ALL completion data, evidence files and history, and deletes every user except <b>admin</b> and <b>demo</b> (demo is reset to viewer / Demo@123). Menus, library and branding are kept. Download a backup first.</p>
      <button disabled={busy} className={danger} onClick={() => prompt('Type CLEAR to erase all data and users except admin and demo') === 'CLEAR' && w(async () => { await call('app_clear', { p_what: 'all' }); await loadU() })}>Erase everything (keep admin & demo)</button></Box></div>)
}
function Backup() {
  const { call, refresh } = useApp(), [files, setFiles] = useState(false)
  const exp = () => run(async () => { const d = await call('app_export', { p_files: files }); download(`ndmo-tracker-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(d), 'application/json') })
  const imp = e => { const f = e.target.files[0]; if (!f) return; f.text().then(t => run(async () => { if (confirm('Restore this backup? Matching items will be overwritten.')) { await call('app_import', { p_data: JSON.parse(t) }); await refresh(); alert('Backup restored') } })) }
  const old = () => run(async () => { const o = JSON.parse(localStorage.getItem('progress') || '{}'), rows = Object.entries(o).map(([k, v]) => ({ k, done: !!v.done, date: v.date, due: v.due, owner: v.owner, ref: v.ref, note: v.note, wf: v.done ? 'Completed' : 'Not started', pct: v.done ? 100 : 0, sample: false })); if (!rows.length) return alert('No data found in this browser'); alert(`${await call('app_bulk_progress', { p_rows: rows, p_wipe: false })} items imported from this browser`); refresh() })
  return (<div className="space-y-4"><Box title="Export (explicit backup)"><p className="mb-2 text-sm text-slate-600">Downloads progress, evidence metadata, menus, branding and user list (no passwords). Take a backup before upgrades or clearing data. Your Supabase data itself is not touched by software updates.</p>
    <label className="mr-3 text-sm"><input type="checkbox" checked={files} onChange={e => setFiles(e.target.checked)} /> Include attached evidence files (larger file)</label><button className={btn} onClick={exp}>Download full backup</button></Box>
    <Box title="Restore"><label className={btn2 + ' inline-block cursor-pointer'}>Restore from backup file<input type="file" accept=".json" onChange={imp} className="hidden" /></label></Box>
    <Box title="Import from the old browser-only version"><p className="mb-2 text-sm text-slate-600">If you used the earlier version on this PC, bring its saved progress into the database.</p><button className={btn2} onClick={old}>Import progress from this browser</button></Box></div>)
}
export default function Admin({ section }) {
  const { isAdmin } = useApp(); if (!isAdmin) return <p className="p-10 text-center text-sm text-red-600">Admin access required.</p>
  const C = { users: Users, security: Security, audit: Audit, branding: Branding, sample: Sample, library: RegLibrary, backup: Backup }[section] || Users
  return (<div className="mx-auto max-w-5xl space-y-4 px-4 py-5"><p className="text-sm text-slate-500">Admin panel <span aria-hidden>›</span> <b className="text-slate-800">{ASEC.find(a => a[0] === section)?.[1]}</b></p><C /></div>)
}
